#!/bin/sh
# Dispatch to a GUI pinentry when the caller sets PINENTRY_USER_DATA=gui
# (e.g. Neovim/Neogit), otherwise use the inline terminal pinentry.
case "$PINENTRY_USER_DATA" in
  gui) exec /usr/bin/pinentry-qt "$@" ;;
  *)   exec /usr/bin/pinentry-tty "$@" ;;
esac
