#!/bin/bash

set -eu
umask 077

if [[ -n ${XDG_RUNTIME_DIR:-} ]]; then
	signal_dir="$XDG_RUNTIME_DIR/omarchy-nvim"
else
	signal_dir="/tmp/omarchy-nvim-$UID"
fi

mkdir -p "$signal_dir"
printf '%s\n' "${1:-unknown}" >"$signal_dir/theme"
